- name: play level varibles
  hosts: all
  vars:
    URL: play.sample.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


# if we declare a varible on play level then all the tasks can access that varible

- name: play level varibles from a file
  hoste: all
  vars_files:
    - sample-vars.yml
    tasks:
      - name: print URL
        ansible.builtin.debug:
          msg: URL = {{URL}}

- name: task level variable
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: hosts.example.com
