- name: conditions
  hosts: localhost
  vars:
    a: abc
  tasks:
    - name: conditions on strings
      debug:
        msg: string condition is true
      when: a == "abc"
    - name: conditions on strings 1
      debug:
        msg: string condition are not true
      when: a != "abc"
## strings should be quoted in when condition
    - name: Number1
      debug:
        msg: Both numbers are equal
      when: b == 10