- name: configute yum repos.
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: add application user
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Project Application User