- name: add application user
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Project Application User
  register: APP_USER_REGISTER

- name: Cleanup Old Contnent
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent


#- name: download and extract {{COMPONENT}}
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

#- name: Copy App content to {{COMPONENT}}
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop

- name: Create App Location
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory
  become_user: "{{APP_USER}}"

- name: Download and Extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: http://nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{APP_LOCATION}}"
    remote_src: yes
  become_user: "{{APP_USER}}"
